services:
  # The Backend (Node.js)
  - type: web
    name: impostor-server
    env: node
    root: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000
    plan: free

  # The Frontend (React/Vite)
  # The Frontend (React/Vite)
  - type: web
    name: impostor-client
    env: static
    root: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_SERVER_URL
        fromService:
          type: web
          name: impostor-server
          property: url
